= Paginación
ifndef::sectiondir[:sectiondir: .]
:imagesdir: {sectiondir}/images
include::../../config/attributes.adoc[]

El mapeo entre direcciones virtuales y físicas puede realizarse de diversas maneras.
La forma más extendida es _la **paginación**, que no es sino un esquema de gestión de la memoria que permite que el espacio de direcciones físico de un proceso no sea continuo_.

// TODO: Ver si meter la tabla de páginas jerarquica (al menos)
// TODO: Otras, solo mencionar y decir en qué consisten.

== Método básico

En la paginación _la memoria física se divide en bloques de tamaño fijo denominados **marcos**, mientras que el espacio de direcciones virtual se divide en bloques del mismo tamaño que los marcos, denominados **páginas**_.
Cuando un proceso va a ser ejecutado sus páginas son cargadas desde el almacenamiento secundario en marcos libres de la memoria física.

La paginación es una forma de _reubicación de las direcciones en tiempo de ejecución_ donde la transformación de las direcciones virtuales en direcciones físicas se realiza de la siguiente manera (véase la ):

. _Cada dirección virtual generada por la CPU es divida en dos partes_: un *número de página* stem:[p] y un *desplazamiento* stem:[d].

. _El número de página es utilizado por la MMU para indexar la **tabla de páginas**_, que contiene el *número de marco* stem:[f] de cada página en la memoria física.

. _El número de marco stem:[f] es combinado con el *desplazamiento* stem:[d]_ para generar la dirección física que va a ser enviada por el bus de direcciones hacia la memoria.

// TODO: Incluir la formula.

El tamaño de las páginas —y el de los marcos— viene definido por el hardware y normalmente es un número entero potencia de 2 que puede variar entre 512 bytes y 16 MB, dependiendo de la arquitectura.
Es decir, si el espacio de direcciones es de stem:[2^m] y el tamaño de página es de stem:[2^n], los stem:[m - n] bits de mayor orden del espacio de direcciones indican el _número de página_, mientras que los stem:[n] bits de menor orden indican el _desplazamiento_ (véase la )

=== Desde el punto de vista de los procesos

Cada página de un proceso requiere un marco.
Por tanto, cuando un proceso llega al sistema:

. _Si el proceso requiere n páginas, el sistema operativo debe escoger n marcos_.
Estos marcos son tomados de la _lista de marcos libres_ que debe mantener el sistema.
Puesto que son escogidos de allí donde los haya libres, _el espacio de direcciones físico puede no ser contiguo aunque los procesos vean un espacio de direcciones virtual contiguo_.

. Los marcos seleccionados son asignados al proceso y _cada página del proceso es cargada en uno_ de dichos marcos.

. _La tabla de páginas es actualizada_ de manera que en la entrada de cada página del proceso se pone el número de marco correspondiente.

Un aspecto importante de la paginación es la diferencia entre como ven los proceso la memoria y como es realmente la memoria física.
Cada proceso ve la memoria como un espacio único que lo contiene sólo a él.
Sin embargo la realidad es que el programa está disperso por la memoria física, que además puede almacenar a otros programas.
_Esto es posible porque en cada momento la tabla de páginas sólo contiene las páginas del proceso actual_.

=== Desde el punto de vista del sistema operativo

Puesto que el sistema operativo es quién gestiona la memoria física, _éste debe mantenerse al tanto de las particularidades de su uso_:

* _Que marcos están asignados y a que página de que proceso o procesos_.

* _Que marcos están disponibles_.

Toda esta información generalmente se guarda en una estructura denominada la _**tabla de marcos**, que tiene una entrada por cada marco de la memoria física_.

Además _el sistema operativo debe mantener una copia de la tabla de páginas para cada proceso en el PCB_, igual que mantiene una copia del contador de programa y del contenido de los registros de la CPU.
Esta copia es utilizada:

* Por _el asignador para sustituir la tabla de páginas hardware cuando realiza un cambio de contexto_.
Por lo tanto el uso de la paginación incrementa el tiempo del cambio de contexto.

* _Para el mapeo manual de direcciones virtuales en físicas_.
Por ejemplo, cuando un proceso realiza una llamada al sistema para realizar una operación de E/S y proporciona una dirección como parámetro, dicha dirección debe ser mapeada manualmente para producir la dirección física correspondiente que será utilizada por el hardware para realizar la operación.

=== Tamaño de las páginas

Una decisión de diseño importante es escoger el tamaño de las páginas adecuado:

* _Con páginas más pequeñas esperamos tener menos fragmentación interna_.
Los marcos son asignados como unidades indivisibles, por lo que si los requerimientos de memoria de un procesos no coinciden con un límite de páginas el último marco asignado no sería utilizado completamente (en ocasiones incluso se podría desperdiciar un marco completo).
A ese fenómeno se lo conoce como _fragmentación interna_

* _Con páginas más grande se pierde menos espacio en la tabla de páginas_.
No olvidemos que cuanto más pequeñas son las páginas más páginas son necesarias y, por tanto, más entradas en la tabla de páginas se necesitan.
Además _la E/S es más eficiente cuanto más datos son transferidos en cada operación_.

Los tamaños de páginas típicos son 4 y 8 KB.
Por ejemplo, normalmente cada entrada en la tabla de paginas es de 4 bytes —aunque esto también puede variar—.
Eso significa que cada entrada puede direccionar a uno de los 2^32^ marcos de la memoria física.
Si suponemos que el tamaño de cada marco es de 4 KB, podemos determinar que el sistema es capaz de direccionar 2^44^ bytes —o 16 TB— de memoria física, para lo que es necesario disponer de una tabla de páginas de 4 MB.

== Soporte hardware de la tabla de páginas

La implementación en hardware de la tabla de páginas puede realizarse de diversas maneras:

* _Como un conjunto de registros dedicados de la CPU_.
Es decir, la tabla de páginas del proceso actual es alojada dentro de la propia CPU, en unos registros destinados a tal fin.

* _Almacenada en la memoria_.
Es decir, la tabla de páginas del proceso actual es alojada en la memoria, normalmente en un formato definido por la CPU.

Debido a la velocidad de los registros de la CPU _la implementación como conjunto de registros es la más eficiente._ Sin embargo _sólo puede ser utilizado para tablas de páginas razonablemente pequeñas_.
El DEC PDP-11 —para el que se diseño el primer UNIX— es un ejemplo de sistema con esta implementación.
En el mismo se utilizaba un espacio de direcciones de 16 bits y un tamaño de páginas de 8 KB, por lo que sólo necesitaba 8 registros dedicados para alojar toda tabla de páginas.

En los sistemas modernos se utilizan tablas de páginas muchos más grandes —de un millón de entradas o más— que difícilmente pueden alojarse en registros dentro de la CPU, ya que alojar tablas de páginas de más de 256 entradas es muy costoso.
Por eso los sistemas actuales almacenan la tabla de páginas del proceso en ejecución en la memoria._ Eso permite disponer tablas de páginas de gran tamaño_ aunque a costa de _necesitar dos acceso a la memoria física por cada acceso a una palabra de la memoria virtualfootnote:[La solución a este problema pasa porque la CPU disponga de una eficiente y pequeña —de entre 64 y 1024 entradas— memoria caché en la que almacenar las entradas de la tabla de página previamente utilizadas en la traducción de las direcciones.
A dicha caché se la denomina TLB (Translation Look-aside Buffer).
Obviamente es necesario que el asignador borre la TLB durante los cambios de contexto.]_.

Para que la MMU pueda conocer la ubicación de la tabla de páginas durante la traducción de las direcciones, _la CPU debe disponer de un registro —el *PTBR* (Page-Table Base Register)— donde se guarda la dirección de la tabla de páginas actual_.
Además esto permite que el cambio de contexto sea más rápido —respecto al uso de registros para almacenar la tabla de páginas— puesto que sólo es necesario carga un único registro más —el PTBR— durante el mismo.

== Protección

La protección de las páginas _se consigue mediante unos *bits de protección* asociados a cada entrada de la tabla de páginas_ y normalmente almacenados en la misma.
Estos bits pueden ser:

* *Solo lectura*.

* *Lectura — Escritura*.
En algunos sistemas hay un bit específico para este permiso, mientras que en otros se utilizan bit separados como: _lectura_, _escritura_ y _ejecución_.

* *Sólo ejecución*.
Que no existen en todas las plataformas.
Por ejemplo, la familia Intel x86 careció de esta característica hasta que AMD la incluyó en su arquitectura AMD64, lo que obligó a Intel a incluirla en las versiones más modernas de su Pentium IV.
El bit —que para ser exacto indica _no ejecución_— fue introducido para evitar cierto tipo de ataques de seguridad.

Durante la traducción de las direcciones la MMU comprueba que el tipo de acceso sea válido.
Si esto no es así, se genera una excepción de violación de protección de memoria, dado que el acceso en un modo o autorizado se considera una instrucciones privilegiada.
Normalmente el sistema operativo responde a dicha excepción terminando el proceso que la generó.

_Además de los bits comentados se suele añadir a cada entrada un **bit de válido**_:

* _Cuando una página es válida_, la pagina asociada está en el espacio de direcciones virtual del proceso.
Es decir, _es legal_.

* _Cuando la página no es inválida_, la página no está asociada al espacio de direcciones virtual del proceso.
Es decir, _es ilegal_.

_El sistema operativo puede utilizar este bit para permitir o denegar el acceso a una página_, por ejemplo porque no le ha asignado un marco ya que no está siendo utilizada por el proceso.
Al igual que con los bits de permisos, los intentos de acceso a una página ilegal generan una excepción.

Por ejemplo, en la vemos el espacio de direcciones virtual y la tabla de páginas de un proceso de 5096 bytes en un sistema con páginas de 1024 bytes.
Puesto que el proceso no ocupa todo el espacio de direcciones, sólo las direcciones de la 0 a la 5119 son válidas.
En dicho ejemplo podemos apreciar varios fenómenos:

* Debido a la fragmentación interna las direcciones de la 5097 a la 5119 son válidas, aunque el proceso solo ocupe hasta la 5096.
Es decir, se está asignando al proceso una porción de memoria que no necesita.

* Las páginas ocupadas por el proceso son válidas.
Pero todas las paginas en direcciones por encima de la 5119 están marcadas como ilegales.
_Así el sistema operativo no tiene que asignar marcos a páginas no utilizadas por el proceso_.

En general los procesos sólo necesitan una porción muy pequeña de su espacio de direcciones virtual.
En esos casos es un desperdicio de memoria crear y almacenar un tabla de página completa con una entrada para cada página del espacio de direcciones.
Para evitarlo _en algunas CPU existe el *PTLR* (Page-Table Length Register) que se utiliza para indicar el tamaño actual de la tabla de página_.
Este valor es comparado por la MMU durante la traducción con el número de página de cada dirección virtual, de manera que las páginas con entradas más allá de la última almacenada en la tabla son consideradas ilegales.

En realidad, tal y como vimos en el <<_el_proceso>>, _lo más común es que los procesos tengan un espacio de direcciones virtual disperso como el de la _.
En la misma podemos observar como el sistema operativo ubica los diferentes componentes del proceso de una forma particular dentro del espacio de direcciones virtual.
Este esquema permite que tanto el _montón_ —a través del mecanismo de asignación dinámica de memoria de `malloc()`— como la pila puedan extenderse, en base a las necesidades de memoria que tenga el proceso, sobre la región de memoria no ocupada.
Esa región también puede ser parcialmente ocupada por librerías de enlace dinámico o por otros objetos compartidos que sean necesitados durante la ejecución del proceso.
_En cualquier caso las páginas de dicha región forman parte del espacio de direcciones virtual pero no tienen marcos de memoria física asignados, en tanto en cuanto el proceso no las vaya a utilizar.
La falta de marco es indicada por el sistema operativo utilizando el bit de válido para denegar el acceso_.

== Páginas compartidas

Una de las ventajas importantes de la paginación es la posibilidad de compartir páginas entre procesos.
Para conseguir esto basta con que _las *páginas compartidas* de los distintos procesos tengan asignadas un mismo marco_.
Esto permite, por ejemplo, que los procesos de un mismo programa puedan compartir las páginas de código o los datos de sólo lectura con el fin de ahorrar memoria.
También permite compartir las páginas de código de una librería compartida enlazada a diferentes procesos.

Compartir páginas no sólo permite ahorrar memoria pues en _los sistemas operativos modernos la memoria compartida (véase el <<_memoria_compartida>>) se implementa mediante páginas compartidas_.
