extends: default
font:
  catalog:
    Ink Free:
      normal: InkFree-normal.ttf
      bold: InkFree-bold.ttf
    ## Default theme fonts
    # Noto Serif supports Latin, Latin-1 Supplement, Latin Extended-A, Greek, Cyrillic, Vietnamese & an assortment of symbols
    Noto Serif:
      normal: GEM_FONTS_DIR/notoserif-regular-subset.ttf
      bold: GEM_FONTS_DIR/notoserif-bold-subset.ttf
      italic: GEM_FONTS_DIR/notoserif-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/notoserif-bold_italic-subset.ttf
    # M+ 1mn supports ASCII and the circled numbers used for conums
    M+ 1mn:
      normal: GEM_FONTS_DIR/mplus1mn-regular-subset.ttf
      bold: GEM_FONTS_DIR/mplus1mn-bold-subset.ttf
      italic: GEM_FONTS_DIR/mplus1mn-italic-subset.ttf
      bold_italic: GEM_FONTS_DIR/mplus1mn-bold_italic-subset.ttf
title-page:
  authors:
    content:
      name_only: "{author}"
      with_email: "{author} <{email}>"
      with_url: "{url}[{author}]"
image:
  align: center
  caption:
    align: inherit
admonition:
  icon:
    time:
      name: fa-clock
      stroke_color: f28500
      size: 24