extends: default
font:
  catalog:
    merge: true
    Ink Free:
      normal: InkFree-normal.ttf
      bold: InkFree-bold.ttf
      italic: InkFree-normal.ttf
      bold_italic: InkFree-bold.ttf
    # M+ 1p supports Latin, Latin-1 Supplement, Latin Extended, Greek, Cyrillic, Vietnamese, Japanese & an assortment of symbols
    # It also provides arrows for ->, <-, => and <= replacements in case these glyphs are missing from font
    Liberation Sans:
      normal: LiberationSans-Regular.ttf
      bold: LiberationSans-Bold.ttf
      italic: LiberationSans-Italic.ttf
      bold_italic: LiberationSans-BoldItalic.ttf
    M+ 1p Fallback: mplus1p-regular-fallback.ttf
    Noto Emoji: notoemoji-subset.ttf
  fallbacks: [M+ 1p Fallback, Noto Emoji]
title-page:
  authors:
    content:
      name_only: "{author}"
      with_email: "{author} <{email}>"
      with_url: "{url}[{author}]"
image:
  align: center
  caption:
    align: inherit
example:
  background_color: fffef7
  border-color: cccccc
sidebar:
  border-color: cccccc
table:
  head:
    background-color: f0f0f0
    font-style: bold
  header-cell:
    background-color: f0f0f0
    font-style: bold
  foot:
    background-color: f0f0f0
    font-style: bold
admonition:
  icon:
    time:
      name: fa-clock
      stroke_color: f28500
      size: 24